version: '3.0'
services:

  nginx:
    container_name: "nginx"
    image: nginx:1.16
    restart: always
    ports:
      - "80:80"
    links:
      - backend
    volumes:
      - ./nginx/default:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/app/src
      - ./logs/:/var/log/nginx/
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend:latest
    restart: always
    tty: true
    working_dir: /var/www/html/app
    volumes:
      - ./:/var/www/html/app
    environment:
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE:-vagrant}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-toor}
    tty: true
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-vagrant}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-toor}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/users.sql
